---
ls:
  .adoc: kebab-case | SCREAMING_SNAKE_CASE | PascalCase
  .md: kebab-case | SCREAMING_SNAKE_CASE
  .puml: kebab-case

  .alloy: kebab-case
  .conf: kebab-case
  .go: snake_case
  .feature: kebab-case
  .hbs: kebab-case
  .json: kebab-case
  .rb: kebab-case
  .svg: kebab-case
  .tf: kebab-case
  .toml: kebab-case

  .yml: kebab-case
  .yaml: kebab-case
  .override.yml: kebab-case
  .override.yaml: kebab-case

  .java: PascalCase
  .kt: PascalCase
  .sh: kebab-case

  .css: kebab-case
  .html: kebab-case
  .js: kebab-case

  Dockerfile: PascalCase
  Vagrantfile: PascalCase

  .babelrc: lowercase
  .env: lowercase
  .dockerignore: lowercase
  .folderslintrc: lowercase
  .gitignore: lowercase
  .gitkeep: lowercase
  .shellcheckrc: lowercase

ignore:
  # commons
  - .git
  - .idea
  - .vscode
  - node_modules
  - target/docs/site
  - target

  - .task

  # linter definitions etc.
  - .editorconfig
  - .hadolint.yml
  - .lychee.toml
  - .ls-lint.yml
  - .markdownlint.yml
  - .yamllint.yml
  - .pre-commit-config.yaml
  - .releaserc.js
