---
version: '3.42.1'

dotenv: ['.env']

vars:
  REPO: https://raw.githubusercontent.com/sommerfeld-io/.github

includes:
  common: https://raw.githubusercontent.com/sommerfeld-io/.github/refs/heads/main/assets/task/common.yml

tasks:

  cleanup:
    desc: 'Cleanup the environment'
    cmds:
      - docker compose down --remove-orphans
      - docker container prune -f
      - docker volume prune -f
      - rm -rf .cache
      - rm -rf node_modules
      - rm -rf target
      - sudo rm -rf .devcontainer/ops
      - sudo rm -f tests/metrics/inspec/baseline/inspec.lock
      - sudo rm -f tests/telemetry/inspec/baseline/inspec.lock
      - find . -type f -exec chmod ugo+r {} +
      - find . -type d -exec chmod 755 {} +
      - find . -name "*.sh" -type f -exec chmod +x {} +

  # ===============================================================================================

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - for: ['yaml', 'filenames', 'folders', 'workflows', 'alloy-config', 'markdown-links']
        cmd: docker compose up lint-{{ .ITEM }} --exit-code-from lint-{{ .ITEM }}
      - for: ['telemetry']
        cmd: docker compose -f tests/{{ .ITEM }}/docker-compose.yml up check-profile --exit-code-from check-profile

  # ===============================================================================================

  run:telemetry:
    desc: 'Run the telemetry stack'
    dir: components/telemetry
    cmds:
      - docker compose down --remove-orphans
      - docker compose up

  run:metrics:dev:
    desc: 'Run the metrics stack for local development'
    dir: components/metrics-dev
    vars:
      ENV_PROD: env = "prod"
      ENV_DEV: env = "dev"
      LOKI_PROD: http://admin-pi.fritz.box:3100/loki/api/v1/push
      LOKI_DEV: http://host.docker.internal:3100/loki/api/v1/push
    cmds:
      - pwd
      - ls -alF
      - cp ../metrics/config/alloy/config.alloy config/alloy/config.alloy
      - sed -i '1i// ! Auto-generated from ../metrics/config/alloy/config.alloy\n// ! DO NOT EDIT THIS FILE DIRECTLY - Changes will be overwritten\n' config/alloy/config.alloy
      - sed -i 's|{{ .ENV_PROD }}|{{ .ENV_DEV }}|' config/alloy/config.alloy
      - sed -i 's|{{ .LOKI_PROD }}|{{ .LOKI_DEV }}|' config/alloy/config.alloy
      # - docker compose down --remove-orphans
      # - docker compose up
