---
apiVersion: 1
groups:
  - orgId: 1
    name: node-exporter
    folder: system
    interval: 5m
    rules:
      # -----------------------------------------------------------------------
      - uid: root-fs-used
        title: Root FS Used
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              adhocFilters: []
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              exemplar: false
              expr: |
                (
                  (node_filesystem_size_bytes{job="system-metrics", mountpoint="/", fstype!="rootfs"}
                    - node_filesystem_avail_bytes{job="system-metrics", mountpoint="/", fstype!="rootfs"})
                  / node_filesystem_size_bytes{job="system-metrics", mountpoint="/", fstype!="rootfs"}
                ) * 100
              format: time_series
              instant: true
              interval: ""
              intervalFactor: 1
              intervalMs: 15000
              maxDataPoints: 43200
              range: false
              refId: A
              step: 240
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 75
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        dashboardUid: rYdddlPWk
        panelId: 154
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          __dashboardUid__: rYdddlPWk
          __panelId__: "154"
          description: Too little space left on device. Root FS usage is above 75%.
          summary: Root FS usage is above threshold
        labels:
          notification/channel: google-chat
          notification/enabled: "true"
          severity: medium
        isPaused: false
        notification_settings:
          receiver: grafana-default-email
      # -----------------------------------------------------------------------
      - uid: ram-used
        title: RAM Used
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              adhocFilters: []
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              exemplar: false
              expr: (1 - (node_memory_MemAvailable_bytes{job="system-metrics"} / node_memory_MemTotal_bytes{job="system-metrics"})) * 100
              format: time_series
              instant: true
              interval: ""
              intervalFactor: 1
              intervalMs: 15000
              maxDataPoints: 43200
              range: false
              refId: A
              step: 240
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 75
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        dashboardUid: rYdddlPWk
        panelId: 16
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          __dashboardUid__: rYdddlPWk
          __panelId__: "16"
          description: RAM usage is above 75%.
          summary: RAM usage is above threshold
        labels:
          notification/channel: google-chat
          notification/enabled: "true"
          severity: medium
        isPaused: false
        notification_settings:
          receiver: grafana-default-email
