---
services:

  node_exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node_exporter
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - --path.rootfs=/host
    pid: host
    network_mode: host
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9100/"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  alloy:
    image: grafana/alloy:v1.11.2
    container_name: alloy
    restart: unless-stopped
    environment:
      # additional data which should be available in config.alloy
      - HOSTNAME=${HOSTNAME}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./config/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - 12345:12345
      - 4317:4317
      - 4318:4318
    healthcheck:  # sort of dummy health check due to no wget or curl in image
      test: ["CMD", "/bin/sh", "-c", "alloy --version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 9110:8080
    privileged: true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
