---
global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus-grafana-stack'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'workstation-and-raspi'
    scrape_interval: 15s
    static_configs:
      - targets:
          - caprica.fritz.box:9100
          - kobol.fritz.box:9100
          - admin-pi.fritz.box:9100
        labels:
          group: "node-metrics"
      - targets:
          - caprica.fritz.box:9110
          - kobol.fritz.box:9110
          - admin-pi.fritz.box:9110
        labels:
          group: "docker-metrics"

  - job_name: 'websites'
    metrics_path: /probe
    params:
      module: [http_2xx]
    scrape_interval: 60s
    static_configs:
      - targets:
          - www.fb-brunnenbau.de
          - www.minifigs.de
          - www.sommerfeld.io
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
