---
apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    uid: prometheus
    password: # <string> database password, if used
    user: # <string> database user, if used
    database: # <string> database name, if used
    basicAuth: true
    basicAuthUser: admin
    basicAuthPassword: admin
    withCredentials: # <bool> enable/disable with credentials headers
    isDefault: true
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:
      tlsCACert: "..."
      tlsClientCert: "..."
      tlsClientKey: "..."
    version: 1
    editable: true
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: 'http://loki:3100'
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
