{
 "title": "Alloy / Resources",
 "tags": [ "alloy-health" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki Data Source", "query": "loki" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{job=~\"integrations/alloy\"}, cluster)\n"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{job=~\"integrations/alloy\", cluster=~\"$cluster\"}, namespace)\n"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{job=~\"integrations/alloy\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, job)\n"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{job=~\"integrations/alloy\", cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}, instance)\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "stat",
   "description": "Shows if metrics are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(1) and on() ((count(up{job=~\"$job\"} == 1) > 0) and (absent(absent(alloy_resources_process_cpu_seconds_total{job=~\"$job\"})))) or vector(0) and on() ((count(up{job=~\"$job\"}) > 0) and (absent(alloy_resources_process_cpu_seconds_total{job=~\"$job\"})))\n"
    }
   ]
  },
  {
   "title": "Latest metrics received",
   "type": "stat",
   "description": "Shows the timestamp of the latest metrics received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(1) and on() ((count(up{job=~\"$job\"} == 1) > 0) and (absent(absent(alloy_resources_process_cpu_seconds_total{job=~\"$job\"})))) or vector(0) and on() ((count(up{job=~\"$job\"}) > 0) and (absent(alloy_resources_process_cpu_seconds_total{job=~\"$job\"})))\n"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "stat",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage of the Alloy process relative to 1 CPU core.\n\nFor example, 100% means using one entire CPU core.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(alloy_resources_process_cpu_seconds_total{job=~\"integrations/alloy\", cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory (RSS)",
   "type": "timeseries",
   "description": "Resident memory size of the Alloy process.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "alloy_resources_process_resident_memory_bytes{job=~\"integrations/alloy\", cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage collections",
   "type": "timeseries",
   "description": "Rate at which the Alloy process performs garbage collections.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{job=~\"integrations/alloy\", cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[5m])\nand on(instance)\nalloy_build_info{job=~\"integrations/alloy\", cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Number of goroutines which are running in parallel. An infinitely\ngrowing number of these indicates a goroutine leak.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"integrations/alloy\", cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}\nand on(instance)\nalloy_build_info{job=~\"integrations/alloy\", cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory (heap inuse)",
   "type": "timeseries",
   "description": "Heap memory currently in use by the Alloy process.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"integrations/alloy\", cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}\nand on(instance)\nalloy_build_info{job=~\"integrations/alloy\", cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network receive bandwidth",
   "type": "timeseries",
   "description": "Rate of data received across all network interfaces for the machine\nAlloy is running on.\n\nData shown here is across all running processes and not exclusive to\nthe running Alloy process.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(alloy_resources_machine_rx_bytes_total{job=~\"integrations/alloy\", cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network send bandwidth",
   "type": "timeseries",
   "description": "Rate of data sent across all network interfaces for the machine\nAlloy is running on.\n\nData shown here is across all running processes and not exclusive to\nthe running Alloy process.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(alloy_resources_machine_tx_bytes_total{job=~\"integrations/alloy\", cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}