{
 "title": "Service Overview",
 "tags": [ "overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(probe_success,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(probe_success{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_success{\n    instance=~\"$instance\",\n    job=~\"$job\"\n}"
    }
   ]
  },
  {
   "title": "Uptime percentage",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=~\"$instance\", job=~\"$job\"}[$__range]) * 100"
    }
   ]
  },
  {
   "title": "HTTP Status Codes (Blackbox Probe)",
   "type": "timeseries",
   "description": "Based on blackbox probing (= requests from prometheus to the service). Not based on logs. So this is just an indicator which signals if the app is alive or not.",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_http_status_code{\r\n    instance=~\"$instance\",\r\n    job=~\"$job\"\r\n}"
    }
   ]
  },
  {
   "title": "HTTP 2xx percentage",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "targets": [
    {
     "expr": "(\n  count_over_time((probe_http_status_code{instance=~\"$instance\", job=~\"$job\"} >= 200 and probe_http_status_code{instance=~\"$instance\", job=~\"$job\"} < 300)[1m:])\n  /\n  count_over_time(probe_http_status_code{instance=~\"$instance\", job=~\"$job\"}[1m:])\n) * 100"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{\r\n    instance=~\"$instance\",\r\n    job=~\"$job\"\r\n}"
    }
   ]
  },
  {
   "title": "TSL",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "probe_http_ssl{job=~\"$job\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"$job\", instance=~\"$instance\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_tls_version_info{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP Probe Phases Duration: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Probe Phases Duration",
     "type": "timeseries",
     "description": "Duration of http request by phase, summed over all redirects",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    }
   ]
  }
 ]
}